import type {Weather} from '../core/types';
export class Soundscape {
 private context:AudioContext|null=null;private master:GainNode|null=null;private rain:GainNode|null=null;private engine:OscillatorNode|null=null;private engineGain:GainNode|null=null;private ambient:GainNode|null=null;private nextBird=0;private step=0;enabled=true;
 async start(){if(this.context){await this.context.resume();return;}this.context=new AudioContext();const c=this.context;this.master=c.createGain();this.master.gain.value=.32;this.master.connect(c.destination);const noise=c.createBuffer(1,c.sampleRate*3,c.sampleRate);let last=0;for(let i=0;i<noise.length;i++){last=(last+Math.random()*.12-.06)*.98;noise.getChannelData(0)[i]=last;}
 const layer=(freq:number,gain:number)=>{const n=c.createBufferSource();n.buffer=noise;n.loop=true;const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=freq;const g=c.createGain();g.gain.value=gain;n.connect(filter).connect(g).connect(this.master!);n.start();return g;};this.rain=layer(3200,0);this.ambient=layer(520,.22);this.engine=c.createOscillator();this.engine.type='sawtooth';this.engine.frequency.value=55;const filter=c.createBiquadFilter();filter.frequency.value=230;this.engineGain=c.createGain();this.engineGain.gain.value=.006;this.engine.connect(filter).connect(this.engineGain).connect(this.master);this.engine.start();}
 setEnabled(on:boolean){this.enabled=on;if(this.master)this.master.gain.setTargetAtTime(on?.32:0,this.context!.currentTime,.2);}
 private tone(freq:number,duration:number,gain:number,type:OscillatorType='sine',pan=0){if(!this.context||!this.master||!this.enabled)return;const c=this.context,o=c.createOscillator(),g=c.createGain(),p=c.createStereoPanner();o.type=type;o.frequency.value=freq;p.pan.value=pan;g.gain.setValueAtTime(0,c.currentTime);g.gain.linearRampToValueAtTime(gain,c.currentTime+.015);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g).connect(p).connect(this.master);o.start();o.stop(c.currentTime+duration+.02);}
 horn(pan=0){this.tone(392,.33,.17,'sawtooth',pan);this.tone(494,.32,.1,'sine',pan);}
 update(dt:number,t:number,weather:Weather,time:number,moving:boolean,speed:number,district:string){if(!this.context)return;const c=this.context;this.rain!.gain.setTargetAtTime(weather==='rain'?.85:0,c.currentTime,.8);this.engine!.frequency.setTargetAtTime(42+Math.abs(speed)*5,c.currentTime,.2);this.engineGain!.gain.setTargetAtTime(speed===0?.007:.025,c.currentTime,.3);this.ambient!.gain.setTargetAtTime(district.toLowerCase().includes('park')?.1:.3,c.currentTime,1);if(t>this.nextBird&&time>360&&time<1140&&weather!=='rain'){this.nextBird=t+5+Math.random()*7;this.tone(2300+Math.random()*800,.14,.08,'sine',Math.random()*2-1);setTimeout(()=>this.tone(2900,.11,.05,'sine'),180);}this.step+=dt;if(moving&&this.step>.36){this.step=0;this.tone(80,.07,.14,'triangle');}}
}
