import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createWorld} from '../world/city';
import {Simulation} from '../simulation/simulation';
import {PlayerController} from '../player/controller';
import {Crowd} from '../player/characters';
import {Traffic} from '../vehicles/traffic';
import {Environment} from '../world-effects';
import {Soundscape} from '../audio/soundscape';
import {GameUI} from '../ui/ui';
import {Interactions,escapeHtml} from './interactions';
import {distance} from './geometry';
import type {Place,Resident} from './types';
import {SHOP_CATALOG} from '../data/economy';
const SAVE_KEY='navapur.save.v1';
export class Game {
 scene=new T.Scene();camera=new T.PerspectiveCamera(58,innerWidth/innerHeight,.1,1600);renderer:T.WebGLRenderer;world=createWorld();sim=new Simulation(this.world.places,this.world.roadCoordinates);traffic=new Traffic();crowd=new Crowd();audio=new Soundscape();environment:Environment;player:PlayerController;ui:GameUI;interactions:Interactions;
 started=false;debug=false;timeScale=1;quality:'high'|'balanced'='high';waypoint:{x:number,z:number,name:string}|null=null;progress={bought:false,ate:false,talked:false,drove:false};private last=0;elapsed=0;private fps=60;private uiClock=0;private autoSave=0;private lastCollision=-100;private nearby:{type:'shop'|'person'|'place'|'vehicle',label:string,target:Place|Resident|null}|null=null;private marker:T.Group;private headlight:T.SpotLight;private navLines:T.LineSegments;private nameLayer:HTMLDivElement;private perfLines:T.BufferGeometry;private notices=0;
 constructor(){
 this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setSize(innerWidth,innerHeight);this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.renderer.outputColorSpace=T.SRGBColorSpace;const canvas=this.renderer.domElement;canvas.className='city-canvas';canvas.setAttribute('aria-label','Navapur interactive 3D city. Use W A S D to walk and drag to look around.');canvas.tabIndex=0;document.getElementById('app')!.prepend(canvas);
 const env=new RoomEnvironment();const pmrem=new T.PMREMGenerator(this.renderer);const generated=pmrem.fromScene(env,.04);this.scene.environment=generated.texture;this.scene.environmentIntensity=.38;env.dispose();pmrem.dispose();this.scene.add(this.world.group,this.traffic.group,this.crowd.group);this.environment=new Environment(this.scene);this.player=new PlayerController(this.camera,canvas,this.world.colliders,this.world.bounds);this.scene.add(this.player.avatar.group);this.player.reset(this.sim.player);
 this.ui=new GameUI({onAction:(a,v)=>{if(a==='rest'){this.sim.player.stamina=100;this.sim.player.health=Math.min(100,this.sim.player.health+8);this.sim.time=(this.sim.time+30)%1440;this.ui.toast('A quiet half-hour. You feel refreshed.');this.ui.closePanel();}else this.interactions.act(a,v);},hasSave:this.hasSave()});this.ui.setMap(this.world.places,this.world.roadCoordinates,this.world.bounds);this.interactions=new Interactions(this);
 this.marker=new T.Group();const ring=new T.Mesh(new T.TorusGeometry(.8,.04,6,36),new T.MeshBasicMaterial({color:'#e9b875',depthTest:false}));ring.rotation.x=Math.PI/2;this.marker.add(ring);const pin=new T.Mesh(new T.OctahedronGeometry(.25),new T.MeshBasicMaterial({color:'#e9b875',depthTest:false}));pin.position.y=2.7;this.marker.add(pin);this.scene.add(this.marker);this.marker.visible=false;
 this.headlight=new T.SpotLight('#fff0ce',0,48,.48,.5,1);this.headlight.target=new T.Object3D();this.scene.add(this.headlight,this.headlight.target);
 const vertices:number[]=[];for(const x of this.world.roadCoordinates)for(const z of this.world.roadCoordinates){vertices.push(x-10,.1,z-10,x-10,.1,z+10,x-10,.1,z-10,x+10,.1,z-10);}this.perfLines=new T.BufferGeometry();this.perfLines.setAttribute('position',new T.Float32BufferAttribute(vertices,3));this.navLines=new T.LineSegments(this.perfLines,new T.LineBasicMaterial({color:'#91d2c5',transparent:true,opacity:.7}));this.scene.add(this.navLines);this.nameLayer=document.createElement('div');this.nameLayer.className='npc-debug-layer';document.getElementById('app')!.append(this.nameLayer);
 window.addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);});window.addEventListener('keydown',e=>this.key(e));document.addEventListener('visibilitychange',()=>{if(document.hidden){this.player.keys.clear();if(this.started&&!this.ui.isPanelOpen)this.interactions.pause();}});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.ui.toast('The graphics context paused. Reload to continue from your last save.');});window.addEventListener('beforeunload',()=>{if(this.started)this.save(false);});(window as any).__navapur=this;requestAnimationFrame(t=>this.frame(t));
 }
 private hasSave(){try{return !!localStorage.getItem(SAVE_KEY);}catch{return false;}}
 start(){this.started=true;this.ui.setStarted(true);this.ui.closePanel();this.player.reset(this.sim.player);void this.audio.start().catch(()=>this.ui.toast('City sounds are unavailable in this browser.'));this.ui.toast('Welcome to Purana Bazaar. Drag to look around; W A S D to walk.');}
 setQuality(q:'high'|'balanced'){this.quality=q;this.renderer.setPixelRatio(q==='high'?Math.min(devicePixelRatio,1.6):1);this.renderer.shadowMap.enabled=q==='high';this.renderer.setSize(innerWidth,innerHeight);}
 private key(e:KeyboardEvent){if((e.target as HTMLElement).matches('input,select,textarea')||e.repeat)return;if(['F3','F5','F9','KeyI','KeyM','Tab'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(this.ui.isPanelOpen)this.ui.closePanel();else if(this.started)this.interactions.pause();return;}if(!this.started)return;if(e.code==='F5'){this.save();return;}if(e.code==='F9'){this.load();return;}if(e.code==='F3'){this.debug=!this.debug;return;}if(this.ui.isPanelOpen)return;const action:Record<string,string>={KeyI:'inventory',KeyM:'map',KeyJ:'journal',KeyE:'interact',KeyV:'vehicle',KeyP:'pause'};if(action[e.code])this.interactions.act(action[e.code]);if(e.code==='KeyC')this.player.firstPerson=!this.player.firstPerson;if(e.code==='KeyH')this.audio.horn();if(e.code==='KeyL'&&this.traffic.controlled){this.traffic.controlled.headlights=!this.traffic.controlled.headlights;this.ui.toast(this.traffic.controlled.headlights?'Headlights on':'Headlights off');}}
 toggleVehicle(){if(this.traffic.controlled){if(!this.traffic.exit(this.sim.player,(x,z,r)=>this.player.blocked(x,z,r)))this.ui.toast('There is no clear space to exit. Move the vehicle a little.');else{this.player.inVehicle=false;this.ui.toast('Back on foot.');}}else{const v=this.traffic.nearest(this.sim.player);if(!v){this.ui.toast('Stand beside a stopped vehicle to drive.');return;}this.traffic.enter(v,this.sim.player);this.player.inVehicle=true;this.player.yaw=v.heading;this.progress.drove=true;this.ui.toast(`${v.kind==='auto'?'Auto-rickshaw':v.kind} · W accelerate · S reverse · Space brake · V leave`);}}
 private findInteraction(){const p=this.sim.player;this.nearby=null;if(this.traffic.controlled){this.nearby={type:'vehicle',label:'Leave vehicle',target:null};return;}const candidates:Array<{d:number,type:'shop'|'person'|'place',label:string,target:Place|Resident}>=[];for(const place of this.world.places){const d=distance(p,place.entrance);const inside=place.interior&&distance(p,place.interior)<4;if(d<5||inside)candidates.push({d:inside?1:d,type:SHOP_CATALOG[place.kind]?'shop':'place',label:SHOP_CATALOG[place.kind]?`Visit ${place.name}`:`Explore ${place.name}`,target:place});}for(const r of this.sim.residents){const d=distance(p,r);if(d<3)candidates.push({d:d+.8,type:'person',label:`Talk to ${r.name.split(' ')[0]}`,target:r});}candidates.sort((a,b)=>a.d-b.d);this.nearby=candidates[0]??null;if(!this.nearby&&this.traffic.nearest(p))this.nearby={type:'vehicle',label:'Drive nearby vehicle',target:null};}
 interact(){this.findInteraction();if(!this.nearby){this.ui.toast('Walk closer to a neighbour, storefront or vehicle.');return;}const n=this.nearby;if(n.type==='person')this.interactions.talk(n.target as Resident);else if(n.type==='shop')this.interactions.openShop(n.target as Place);else if(n.type==='vehicle')this.toggleVehicle();else{const p=n.target as Place;const descriptions:Partial<Record<Place['kind'],string>>={home:'A quiet courtyard and a place to catch your breath.',park:'Shade, birdsong and a welcome break from the city streets.',school:'Students and teachers gather here through the working day.',hospital:'Navapur’s medical team responds when residents need help.',police:'The neighbourhood police patrol the streets and respond to city incidents.',station:'A busy meeting point for commuters, drivers and the next journey.',temple:'A neighbourhood place of worship and quiet reflection.',mosque:'A community place of worship in the heart of the neighbourhood.',church:'A peaceful place of worship shared by the local community.'};this.ui.openPanel(p.name,`<p class="panel-intro">${escapeHtml(p.hindi)}<br>${descriptions[p.kind]||'Part of the everyday rhythm of Navapur.'}</p>${['home','park','hospital'].includes(p.kind)?'<button class="panel-button" data-action="rest">Rest for 30 minutes</button>':''}<button class="panel-button" data-action="job">Ask about delivery work</button>`,p.kind.toUpperCase());}}
 save(notify=true){try{localStorage.setItem(SAVE_KEY,JSON.stringify({version:1,simulation:this.sim.save(),vehicles:this.traffic.serialize(),controlled:this.traffic.controlled?.id??null,progress:this.progress,settings:{quality:this.quality,timeScale:this.timeScale,audio:this.audio.enabled},waypoint:this.waypoint}));if(notify)this.ui.toast('Journey saved on this device.');}catch{if(notify)this.ui.toast('Saving is unavailable. Check this browser’s storage settings.');}}
 load(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw){this.ui.toast('No saved journey yet.');return;}const data=JSON.parse(raw);if(data.version!==1||typeof data.simulation!=='string'||!Array.isArray(data.vehicles)||data.vehicles.length!==this.traffic.vehicles.length)throw new Error('Invalid save');const ids=new Set<string>();for(const v of data.vehicles){if(typeof v!=='object'||!v||!this.traffic.vehicles.some(t=>t.id===v.id)||ids.has(v.id)||!['x','z','heading','fuel','damage','target'].every(k=>Number.isFinite(v[k]))||Math.abs(v.x)>this.world.bounds+10||Math.abs(v.z)>this.world.bounds+10||v.fuel<0||v.fuel>100||v.damage<0||v.damage>100||!Number.isInteger(v.target)||v.target<0||v.target>3||typeof v.parked!=='boolean')throw new Error('Invalid vehicle save');ids.add(v.id);}if(data.controlled!==null&&!ids.has(data.controlled))throw new Error('Invalid controlled vehicle');if(!data.progress||!['bought','ate','talked','drove'].every(k=>typeof data.progress[k]==='boolean'))throw new Error('Invalid progress');const parsed=JSON.parse(data.simulation);if(Math.abs(parsed.player?.x)>this.world.bounds||Math.abs(parsed.player?.z)>this.world.bounds)throw new Error('Invalid location');const r=this.sim.load(data.simulation);if(!r.ok){this.ui.toast(r.message);return;}this.traffic.restore(data.vehicles);this.progress=data.progress;this.waypoint=data.waypoint&&Number.isFinite(data.waypoint.x)&&Number.isFinite(data.waypoint.z)&&typeof data.waypoint.name==='string'?data.waypoint:null;this.setQuality(data.settings?.quality==='balanced'?'balanced':'high');this.timeScale=[.5,1,10].includes(data.settings?.timeScale)?data.settings.timeScale:1;this.audio.setEnabled(data.settings?.audio!==false);this.player.inVehicle=false;if(data.controlled){this.traffic.controlled=this.traffic.vehicles.find(v=>v.id===data.controlled)!;this.player.inVehicle=true;}this.start();this.ui.toast('Welcome back. Your journey has been restored.');}catch{this.ui.toast('That save could not be read. Your current journey is unchanged.');}}
 private frame(timestamp:number){requestAnimationFrame(t=>this.frame(t));const dt=Math.min(.05,(timestamp-this.last)/1000||.016);this.last=timestamp;this.fps+=(1/Math.max(dt,.001)-this.fps)*.04;const paused=this.started&&this.ui.isPanelOpen;const tick=paused?0:dt;this.elapsed+=tick;
 if(!paused){this.sim.timeScale=this.timeScale;this.sim.update(dt);this.traffic.update(dt,this.elapsed,this.sim.weather,this.sim.player,this.player.keys,this.started,(x,z,r)=>this.player.blocked(x,z,r),(x,z)=>{if(this.elapsed-this.lastCollision>6){this.lastCollision=this.elapsed;this.sim.triggerEvent('collision',x,z);this.audio.horn();}});}
 if(this.started)this.player.update(dt,this.sim.player,this.elapsed,!paused);else{this.camera.position.set(-5.5,4.8,43);this.camera.lookAt(10,3.1,-7);this.player.avatar.group.position.set(this.sim.player.x,0,this.sim.player.z);this.player.avatar.group.rotation.y=Math.PI;}
 this.environment.update(tick,this.elapsed,this.sim.time,this.sim.weather,this.sim.player,this.sim.events);this.world.update(this.sim.time,this.sim.weather);this.crowd.update(this.sim.residents,this.sim.player,this.elapsed,this.sim.weather);
 const v=this.traffic.controlled;this.headlight.intensity=v?.headlights?50:0;if(v){this.headlight.position.set(v.x+Math.sin(v.heading),1,v.z+Math.cos(v.heading));this.headlight.target.position.set(v.x+Math.sin(v.heading)*15,0,v.z+Math.cos(v.heading)*15);}
 this.marker.visible=!!this.waypoint;if(this.waypoint){this.marker.position.set(this.waypoint.x,.17,this.waypoint.z);this.marker.children[1].rotation.y=this.elapsed;this.marker.children[1].position.y=2.6+Math.sin(this.elapsed*2)*.18;}
 const district=[...this.world.districts].sort((a,b)=>distance(a,this.sim.player)-distance(b,this.sim.player))[0];this.audio.update(tick,this.elapsed,this.sim.weather,this.sim.time,this.player.moving, v?.speed??0,district.name);this.uiClock+=dt;this.autoSave+=tick;
 if(this.uiClock>.12){this.uiClock=0;this.findInteraction();const minutes=Math.floor(this.sim.time);const hour=Math.floor(minutes/60);const time=`${String(hour%12||12).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')} ${hour>=12?'PM':'AM'}`;this.ui.update({district:district.name,subtitle:district.subtitle,time,day:this.sim.day,weather:this.sim.weather,cash:this.sim.player.cash,health:this.sim.player.health,stamina:this.sim.player.stamina,hunger:this.sim.player.hunger,x:this.sim.player.x,z:this.sim.player.z,heading:this.player.yaw,speed:v?Math.round(Math.abs(v.speed)*3.6):undefined,mode:v?`${v.kind} · Fuel ${Math.round(v.fuel)}% · Condition ${Math.round(100-v.damage)}%`:'on foot',interaction:this.nearby?.label,fuel:v?.fuel,residents:this.crowd.activeCount,vehicles:this.traffic.vehicles.length,activeAI:this.sim.residents.filter(r=>r.tier==='near').length,fps:Math.round(this.fps),debug:this.debug,waypoint:this.waypoint,quests:[{label:'Find your first cup of chai',done:this.progress.bought},{label:'Meet someone from the neighbourhood',done:this.progress.talked},{label:'Take an auto for a spin',done:this.progress.drove}]});this.updateDebug();if(this.sim.completedEvents.length>this.notices){this.notices=this.sim.completedEvents.length;this.ui.toast('City services have resolved an incident. Life returns to its rhythm.');}}
 if(this.started&&this.autoSave>60&&!paused){this.autoSave=0;this.save(false);}this.renderer.render(this.scene,this.camera);
 }
 private updateDebug(){this.navLines.visible=this.debug;this.nameLayer.hidden=!this.debug;if(!this.debug)return;const labels=this.sim.residents.filter(r=>distance(r,this.sim.player)<28).slice(0,15).map(r=>{const p=new T.Vector3(r.x,2.35,r.z).project(this.camera);if(p.z>1||p.z<0)return '';return `<span style="left:${(p.x*.5+.5)*innerWidth}px;top:${(-p.y*.5+.5)*innerHeight}px">${escapeHtml(r.name)} · ${escapeHtml(r.activity)}<small>${r.tier} · ${escapeHtml(r.goal)}</small></span>`;});this.nameLayer.innerHTML=`<div class="debug-stats">${this.renderer.info.render.calls} draw calls · ${Math.round(this.renderer.info.render.triangles/1000)}k triangles<br>${this.sim.residents.length} residents · ${this.sim.residents.filter(r=>r.tier==='near').length} full AI · ${this.traffic.vehicles.length} vehicles<br>${escapeHtml(this.sim.law)} · ${this.sim.events.filter(e=>!e.resolved).length} active incidents</div>${labels.join('')}`;}
}
