import * as T from 'three';
import {Sky} from 'three/addons/objects/Sky.js';
import type {CityEvent,Weather} from './core/types';
export class Environment {
 sun=new T.DirectionalLight('#ffe3b5',3.2);hemisphere=new T.HemisphereLight('#bfd6d7','#8c7863',2);sky=new Sky();rain:T.Points;fire:T.InstancedMesh;smoke:T.InstancedMesh;private dummy=new T.Object3D();private rainPositions:Float32Array;private light=new T.PointLight('#ffa03d',0,30,2);private birds:T.InstancedMesh;private lastLighting=-1;
 constructor(private scene:T.Scene){scene.add(this.sun,this.hemisphere);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-75,right:75,top:75,bottom:-75,near:1,far:320});this.sun.shadow.bias=-.0003;this.sun.shadow.normalBias=.04;this.sun.shadow.radius=3;scene.add(this.sun.target);this.sky.scale.setScalar(4500);this.sky.material.uniforms.turbidity.value=4;this.sky.material.uniforms.rayleigh.value=1.7;this.sky.material.uniforms.mieCoefficient.value=.005;this.sky.material.uniforms.mieDirectionalG.value=.84;scene.add(this.sky);scene.fog=new T.FogExp2('#bcbcaf',.0028);
 this.rainPositions=new Float32Array(2500*3);for(let i=0;i<2500;i++){this.rainPositions[i*3]=(Math.random()-.5)*110;this.rainPositions[i*3+1]=Math.random()*45;this.rainPositions[i*3+2]=(Math.random()-.5)*110;}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(this.rainPositions,3));this.rain=new T.Points(geo,new T.PointsMaterial({color:'#d9e2e2',size:.085,transparent:true,opacity:.65,depthWrite:false}));scene.add(this.rain);
 this.fire=new T.InstancedMesh(new T.SphereGeometry(1,8,6),new T.MeshBasicMaterial({color:'#ffac45',transparent:true,opacity:.87,depthWrite:false}),72);this.fire.frustumCulled=false;this.smoke=new T.InstancedMesh(new T.SphereGeometry(1,8,6),new T.MeshStandardMaterial({color:'#615d56',transparent:true,opacity:.27,depthWrite:false}),36);this.smoke.frustumCulled=false;scene.add(this.fire,this.smoke,this.light);
 this.birds=new T.InstancedMesh(new T.ConeGeometry(.12,.8,3),new T.MeshBasicMaterial({color:'#454a42'}),16);scene.add(this.birds);
 }
 update(dt:number,elapsed:number,time:number,weather:Weather,p:{x:number,z:number},events:CityEvent[]){const angle=(time/1440)*Math.PI*2-Math.PI/2;const elevation=Math.sin(angle);const daylight=T.MathUtils.clamp((elevation+.15)*2,0,1);if(Math.abs(time-this.lastLighting)>.3||this.lastLighting<0){this.lastLighting=time;const sunPos=new T.Vector3(-.6,elevation,.3).normalize();this.sky.material.uniforms.sunPosition.value.copy(sunPos);this.sun.intensity=daylight*(weather==='clear'?3.3:weather==='cloudy'?1.6:.8)+.03;this.sun.color.set(daylight>.5?'#ffdfb2':'#9cadd6');this.hemisphere.intensity=.17+daylight*(weather==='rain'?1:1.65);this.sky.material.uniforms.turbidity.value=weather==='rain'?15:weather==='cloudy'?9:4;const fog=this.scene.fog as T.FogExp2;fog.color.set(weather==='rain'?'#8d9b9c':daylight<.15?'#172633':'#c0bcae');fog.density=weather==='rain'?.009:daylight<.15?.006:.003;this.sky.material.uniforms.rayleigh.value=daylight<.15?.1:1.7;}
 this.sun.position.set(p.x-60,80+Math.max(0,elevation)*70,p.z+50);this.sun.target.position.set(p.x,0,p.z);this.rain.visible=weather==='rain';if(this.rain.visible){this.rain.position.set(p.x,0,p.z);for(let i=0;i<2500;i++){this.rainPositions[i*3+1]-=dt*22;if(this.rainPositions[i*3+1]<0)this.rainPositions[i*3+1]=45;this.rainPositions[i*3]+=.5*dt;if(this.rainPositions[i*3]>55)this.rainPositions[i*3]=-55;}this.rain.geometry.attributes.position.needsUpdate=true;}
 const active=events.filter(e=>!e.resolved&&e.type==='fire').slice(0,3);let f=0,s=0;for(const e of active){for(let i=0;i<24;i++){const phase=(elapsed*.7+i*.137)%1;this.dummy.position.set(e.x+Math.sin(i*2.4)*1.5*(1-phase),.3+phase*4,e.z+Math.cos(i*1.6)*1.5*(1-phase));this.dummy.scale.set((1-phase)*.6+.1,(1-phase)*1.1+.2,(1-phase)*.6+.1);this.dummy.updateMatrix();this.fire.setMatrixAt(f++,this.dummy.matrix);}for(let i=0;i<12;i++){const phase=(elapsed*.13+i/12)%1;this.dummy.position.set(e.x+phase*5,2+phase*12,e.z+Math.sin(i)*phase*2);this.dummy.scale.setScalar(.6+phase*2.1);this.dummy.updateMatrix();this.smoke.setMatrixAt(s++,this.dummy.matrix);}}
 this.fire.count=f;this.smoke.count=s;this.fire.instanceMatrix.needsUpdate=true;this.smoke.instanceMatrix.needsUpdate=true;if(active[0]){this.light.position.set(active[0].x,2,active[0].z);this.light.intensity=50+Math.sin(elapsed*9)*8;}else this.light.intensity=0;
 for(let i=0;i<16;i++){const a=elapsed*.08+i*2.3;this.dummy.position.set(Math.sin(a)*60,24+Math.sin(i*1.7)*4,Math.cos(a)*60);this.dummy.rotation.set(Math.PI/2,0,a);this.dummy.scale.set(1+Math.sin(elapsed*8+i)*.4,.6,1);this.dummy.updateMatrix();this.birds.setMatrixAt(i,this.dummy.matrix);}this.birds.instanceMatrix.needsUpdate=true;this.birds.visible=daylight>.1&&weather!=='rain';
 }
}
